name: ROS2 CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_docker:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:jammy
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup ROS2
      uses: ros-tooling/setup-ros@v0.7
      with:
        required-ros-distributions: iron

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-colcon-common-extensions

    # - name: Setup ROS environment
    #   run: |
    #     echo "source /opt/ros/iron/setup.bash" >> ~/.bashrc
    #     source ~/.bashrc

    - name: Checkout example_package
      uses: actions/checkout@v4
      with:
        repository: asurak/assignment_example_pkg
        path: _deps/assignment_example_pkg

    - name: Debug state
      run: |
        ls -la

    - name: Link source
      run: |
        ln -s ../example_package_ros
        ln -s ../example_package_msgs
        ln -s ../_deps/assignment_example_pkg

    - name: Build the workspace
      run: |
        colcon build

    - name: Run tests
      run: |
        colcon test
        colcon test-result --verbose